apiVersion: v1
kind: Namespace
metadata:
  name: pihole-privileged
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-ftl.conf
  namespace: pihole-privileged
data:
  pihole-FTL.conf: |
    MAXDBDAYS=7
    LOGFILE=/var/log/pihole/pihole-FTL.log
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: whitelist.txt
  namespace: pihole-privileged
data:
  whitelist.txt: |
    ichnaea.netflix.com
    nrdp.nccp.netflix.com
    collector-medium.lightstep.com
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adlists.list
  namespace: pihole-privileged
data:
  adlists.list: |
    https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    https://mirror1.malwaredomains.com/files/justdomains
    http://sysctl.org/cameleon/hosts
    https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
    https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
    https://hosts-file.net/ad_servers.txt
    https://blocklist.site/app/dl/tracking
    https://blocklist.site/app/dl/malware
    https://blocklist.site/app/dl/spam
    https://blocklist.site/app/dl/ads
    https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
    https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
    https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
    https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.2o7Net/hosts
    https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
    https://v.firebog.net/hosts/Easyprivacy.txt
    https://v.firebog.net/hosts/Prigent-Ads.txt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole-privileged
  name: pihole-privileged
  namespace: pihole-privileged
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pihole-privileged
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pihole-privileged
    spec:
      containers:
      - env:
        - name: TZ
          value: Europe/London
        - name: WEBPASSWORD
          value: password
        - name: DNS1
          value: 192.168.1.142#8553
        - name: DNS2
          value: 192.168.1.142#8553
        - name: CONDITIONAL_FORWARDING
          value: 'true'
        - name: CONDITIONAL_FORWARDING_DOMAIN
          value: webster.home
        - name: CONDITIONAL_FORWARDING_IP
          value: 192.168.1.254
        image: pihole/pihole:4.3.2-1
        imagePullPolicy: IfNotPresent
        name: pihole-privileged
        ports:
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: dchp
          containerPort: 67
          protocol: UDP
        - name: web
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        resources:
          requests:
            cpu: "20m"
            memory: "512Mi"
          limits:
            cpu: "250m"
            memory: "896Mi"
        readinessProbe:
          exec:
            command: ['dig', '@127.0.0.1', 'cnn.com']
          timeoutSeconds: 20
          initialDelaySeconds: 5
          periodSeconds: 60
        livenessProbe:
          tcpSocket:
            port: dns-tcp
          initialDelaySeconds: 15
          periodSeconds: 30
        volumeMounts:
        - name: etc-pihole
          mountPath: /etc/pihole
        - name: etc-dnsmasq
          mountPath: /etc/dnsmasq.d
        - name: var-log
          mountPath: /var/log
        - name: var-log-lighttpd
          mountPath: /var/log/lighttpd
        - name: ftlconf
          mountPath: /etc/pihole/pihole-FTL.conf
          subPath: pihole-FTL.conf
        - name: whitelist
          mountPath: /etc/pihole/whitelist.txt
          subPath: whitelist.txt
        - name: adlists
          mountPath: /etc/pihole/adlists.list
          subPath: adlists.list
      restartPolicy: Always
      volumes:
      - name: etc-pihole
        emptyDir:
          medium: Memory
      - name: etc-dnsmasq
        emptyDir:
          medium: Memory
      - name: var-log
        emptyDir:
          medium: Memory
      - name: var-log-lighttpd
        emptyDir:
          medium: Memory
      - name: ftlconf
        configMap:
          name: pihole-ftl.conf
          items:
            - key: pihole-FTL.conf
              path: pihole-FTL.conf
      - name: whitelist
        configMap:
          name: whitelist.txt
          items:
            - key: whitelist.txt
              path: whitelist.txt
      - name: adlists
        configMap:
          name: adlists.list
          items:
            - key: adlists.list
              path: adlists.list
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-privileged-dnsudp
  namespace: pihole-privileged
spec:
  selector:
    app: pihole-privileged
  ports:
  - protocol: UDP
    port: 53
    name: dnsudp
    targetPort: 53
  type: LoadBalancer
  loadBalancerIP: 192.168.1.141
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-privileged-web
  namespace: pihole-privileged
spec:
  selector:
    app: pihole-privileged
  ports:
  - protocol: TCP
    port: 80
    name: web
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.1.151